---
  - name: Print os facts
    hosts: all

    vars_prompt:
    - name: USERNAME
      prompt: Username
      private: no
    - name: PASSWORD
      prompt: Password
      private: yes

    vars:
      ansible_user: "{{ USERNAME }}"
      ansible_password: "{{ PASSWORD }}"
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"